services:
  postgres:
    container_name: qoco-dev-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=$${DB_PASSWORD}',
          'pg_isready -d $${DB_NAME} -U $${DB_USER}',
        ]
      interval: 5s
      timeout: 2s
      retries: 10