services:
  postgres:
    container_name: qoco-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=$${DB_PASSWORD}',
          'pg_isready -d $${DB_NAME} -U $${DB_USER}',
        ]
      interval: 5s
      timeout: 2s
      retries: 10
  
  backend:
    container_name: qoco-backend
    ports:
      - "3000:3000"
    build:
      context: ../../..
      dockerfile: ./workspaces/backend/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres: 
        condition: service_healthy
